### ISSUE TITLE
Debian instructions in READM.md incorrect.

### ISSUE THREAD

**Issue by SlySven** [phw/peek#120]
I think the line that states:
>` git clone git@github.com:phw/peek.git`

is incorrect, I had to use:
`git clone https://guthub.com/phw/peek.git ./peek`

possibly the original worked for the Project owner because they have keys for write access to the repository?

Also, currently Debian "Jessie" supplies gettext-0.19.3-2 but that provokes a:
>CMake Warning as data/CMakeLists.txt:48 (message):
>  Gettext >= 0.19.7 required for AppData file translation

Fortunately Debian jessie-backports can supply `gettext-0.19.8-1~bpo8+1` which does the job.  You may also want to ensure that you have the `ffmpeg` package installed - I didn't - which proved awkward when I selected it to use - but I am getting some use out of this project now (for capturing UI issues with the project I code for: __*[Mudlet](https://github.com/Mudlet/Mudlet): "A cross-platform, open source, and super fast MUD client with scripting in Lua"*__)... :smile:

**Comment by phw** [comment]
Thanks for pointing this out, fixed. Actually it worked for everybody who had a Git account and SSH keys associated for it, write access is not required. That's also the reason why I never realized this doesn't work for anonymous access.

> Also, currently Debian "Jessie" supplies gettext-0.19.3-2 but that provokes a:

As this is really not critical and only affects the AppData localization, which usually doesn't matter for local installs anyway, I won't include any information on this in the README. I think users who care about this can easily find the gettext version in jessie-backports.

> You may also want to ensure that you have the ffmpeg package installed - I didn't - which proved awkward when I selected it to use

I think Jessie does not have ffmpeg, but you can use libav-tools instead, Peek will detect this and use avconv instead of ffmpeg. It has some limitations, e.g. the option to not record the mouse cursor does not work and the avconv backend is generally less tested.

>  Mudlet: "A cross-platform, open source, and super fast MUD client with scripting in Lua")
Cool :)
