### ISSUE TITLE
First frame still has the countdown

### ISSUE THREAD

**Issue by vadi2** [phw/peek#146]
If you paste your gif into Discord, which by default does not play gifs, what I take is the first frame is being shown:

![selection_099](https://user-images.githubusercontent.com/110988/26962115-4fe58d00-4ce4-11e7-8288-e13ef30b6a35.png)

As you can see Peek's countdown is still there.

**Comment by phw** [comment]
Strange indeed. Cannot reproduce, but definitely a bug. Only one question: Do you use the ffmpeg or gnome-shell backend (gnome-shell backend is obviously only used on gnome-shell, but if you are unsure start Peek from command line and it will output the backend used).

**Comment by vadi2** [comment]
ffmpeg.

**Comment by phw** [comment]
This is definitely a timing issue caused by the multi threaded nature of the recording. As I hide the counter and start recording in parallel this seems to overlap. One quick fix would be to add a small timeout. But actually there already is a small delay between Peek starting the recording and the first frame being recorded, as initializing the recorder takes some time, depending on the system. E.g. from invoking ffmpeg to ffmpeg actually capturing the first frame there is some delay while ffmpeg initializes. I would like to avoid adding more artificial delay here.

I will try to start recording on the hide signal of the delay indicator.
