### ISSUE TITLE
symbol lookup error: peek: undefined symbol: gtk_shortcut_label_set_disabled_text

### ISSUE THREAD

**Issue by ucuptimposu** [phw/peek#160]
I'm using Fedora 24 with XFCE desktop, and i was installed peek but, the peek can't running.
the Error message is
`symbol lookup error: peek: undefined symbol: gtk_shortcut_label_set_disabled_text`

have any solutions?

**Comment by phw** [comment]
Can you please give the version of Gtk installed? I though I would actually check for this being available :(

**Comment by phw** [comment]
Also please let me know how you installed Peek: from source or using the Fedora repository in the README?

If you use this repository please note that it was compiled against Fedora 25 and thus might not work on 24 due to older Gtk version. In this case I recommend using the Flatpak version, or if you prefer install from source.

I can still add a runtime check to fix this, will look into it.

**Comment by ucuptimposu** [comment]
version gtk3, the complete version gtk3-3.20.10-1.fc24.x86_64.

i was install manually from 
[https://software.opensuse.org/package/peek](https://software.opensuse.org/package/peek)

**Comment by ucuptimposu** [comment]
And finally i,m installed Fedora 26, worked....

**Comment by lexoyo** [comment]
same here

**Comment by phw** [comment]
@lexoyo The packages at https://software.opensuse.org/package/peek are all for Fedora 25 and later and are compiled against at least GTK 3.22. They won't work on older GTK versions.

For Fedora 24 please install from source: https://github.com/phw/peek#installation
