### ISSUE TITLE
Black recording area and black resulting gif

### ISSUE THREAD

**Issue by SunyataZero** [phw/peek#172]
Hi and thank you for creating this program. I'd like to report a possible bug. For me the recording area is black and the gif file is also black after recording

My OS: Lubuntu 16.04 LTS 64-bit
Processor: Intel Celeron N3150

Grateful for help and with kind regards,
Tord

**Comment by phw** [comment]
For now in version 1.0.3 you have to enable compositing for your window manager. See this FAQ for version 1.0.3: https://github.com/phw/peek/tree/v1.0.3#the-recording-area-is-all-black-how-can-i-record-anything

But good news: The current master release already works without compositing. So if you feel comfortable installing from source you can try this. Otherwise I will hopefully soon create a new release.

**Comment by SunyataZero** [comment]
Thank you for the help! I'll probably try the master version
Kind Regards, Tord

**Comment by hptnc** [comment]
Peek 1.3.1
black line during recording » https://giphy.com/gifs/cY4CKHMQxdBFWXzu7r/html5
