### ISSUE TITLE
Peek is darkening gifs for some reason.

### ISSUE THREAD

**Issue by NolanSyKinsley** [phw/peek#180]
The issue is simple, recordings in Peek are much darker than appear on screen. For instance I did a quick capture of the Peek Github page, which is white, and this is how it appears to me in the finished mp4 https://i.imgur.com/NPnvkmY.png

I am running Manjaro linux, installed Peek using Peek-git from the AUR.

**Comment by phw** [comment]
That is very strange, what desktop environment are you using?

While recording this darkening is not visible inside the Peek window, right?

**Comment by NolanSyKinsley** [comment]
Oh... I think I know what is causing it, shadows from compton. I will have to config compton to exempt peek from shadow effects.

**Comment by PhilipCard** [comment]
I have a problem i'm trying to solve for a while but did not find a solution yet.
When i open Peek on my Ubuntu16.04, the window is black instead of transparent. 
I've tried to uninstall and reinstall the application but always end up with the black window that does not record anything ! 

Does someone has a solution to that problem ? 
Here's a screenshot of my problem : 
![screenshot at 2017-08-30 14 27 26](https://user-images.githubusercontent.com/31930470/30386617-492a1d70-9878-11e7-96b9-088a7460dd6a.png)

**Comment by NolanSyKinsley** [comment]
@PhilipCard I would open up a new issue, you issue is unrelated to the cause of the issue I had in this thread.

**Comment by joonas-fi** [comment]
The problem was Compton's shadows for me too (Peek's window should've been the same color as outside of it):

![image](https://user-images.githubusercontent.com/630151/106726550-2f5d7d80-6613-11eb-85f6-b78293a3fa8f.png)

It took a while to understand what I was seeing, but then it *clicked*: Peek's area selector is mainly transparent (except for its borders), and Compton lazily doesn't draw border shadows only around the borders, but it implements border shadows by drawing a border-blurred rectangle (with an x,y offset) that is the size of the original window!

As @NolanSyKinsley mentioned, you need to exclude Peek from shadows. You can use `$ xprop` to display X properties for any window that help you make a filter for `compton.conf` to exclude the shadow. For Peek the lazy route for me was:

```
shadow-exclude = [
       "name = 'Peek'"
];
```

(your shadow-exclude probably should contain other filters as well, but I left mine out to not distract)

After modifying compton's config, you can run `$ killall -USR1 compton` to reload its config without having to stop-and-start.
