### ISSUE TITLE
huge file in .cache/peek

### ISSUE THREAD

**Issue by xstable** [phw/peek#217]
If you have a look at your .cache/peek-Directory, there you'll find really big file.
On mine, the file: peekSZW20Y.pam is > 2,4GB 

Is this a Bug, or why does those huge files are not removed. Maybe it's better to place such files in /tmp, so that even after reboot the files are removed?!

**Comment by mcampbell508** [comment]
I can confirm this is an issue. 

Had 3+GB free on a machine before recording...

Started recording a gif which was about 20 seconds and system froze due to insufficient space available.

I guess 20 seconds is a bit too long for a gif, but still this seems a bit off, to me.

Awesome tool though, by far the best available on Linux :+1:

**Comment by phw** [comment]
The files are removed after recording, if there are any left over files it is due e.g. Peek being interrupted during recording. Just clean out `.cache/peek`.

Main  reason for huge file and memory usage was the use of ImageMagick. The next release gets rid of this and thus has a way lower temp space usage.

> Maybe it's better to place such files in /tmp, so that even after reboot the files are removed?!

Originally Peek placed the files in $TEMP, but that turned out to being a bad idea as it is a RAM disk on many systems.

**Comment by xstable** [comment]
So please add a kind of garbage collector.
Means on peek startup, check if there are .pam-cache-files which cause from interupted previous sessions, and if yes... remove them.
