### ISSUE TITLE
[flatpak] Problems with save dialog

### ISSUE THREAD

**Issue by glaubersm** [phw/peek#228]
Hi
I installed peek from flathub.
Compare the save dialogs from peek and firefox.
peek shows two duplicated items in side bar (imagens and videos) and some items are missing (documentos, downloads, música, dados and desktop).
Also I can't save the gif to my home. Peek shows no error but the file is not saved.
I use Arch Linux with Gnome 3.26.2, flatpak 0.10

![peek](https://user-images.githubusercontent.com/15967631/32929291-2e83c770-cb3e-11e7-9760-21036168c1fa.png)

![firefox](https://user-images.githubusercontent.com/15967631/32929286-22ea9a10-cb3e-11e7-90c5-f8ea6a2f4097.png)

**Comment by phw** [comment]
That's due of the sandboxing and limited access to the filesystem. As a quick fix for you run

    flatpak --user override --filesystem=home com.uploadedlobster.peek

In the end I am limited to the following choices, all of which currently require some compromises:

1. The status quo with limited file system access. Good from a sandboxing perspective but unsatisfying for the user.

2. Giving access to the entire home folder. Better user experience, but it nullifies some of the advantages of the sandbox. But that's probably what I will do.

3. The best solution would be to use the file chooser portal. That will allow the user to select any location in the file system, and the sandboxed app only gets access to exactly that single file. Downside currently is that the "open in file manager" feature doesn't work well with that (see https://github.com/flatpak/xdg-desktop-portal/issues/95).

Please also note that I have only limited control over the Peek package on flathub. All I can do is opening pull requests on https://github.com/flathub/com.uploadedlobster.peek/ and poking people to act on them. And since I was not good at poking somebody this time the package still was not updated to the latest 1.1.0. Your specific issue was also reported at https://github.com/flathub/com.uploadedlobster.peek/issues/3

For the time being you can also use my own Flatpak repository, see https://github.com/phw/peek#flatpak . I will eventually move the stable builds entirely to flathub, but only once this gets more automated and I gain more control over it.

**Comment by glaubersm** [comment]
Thank you fot your detailed post.
Override command works to save files to home, but two problmens remain: it's not possible to save the gif to my ntfs partition and bookmarks ("DADOS" and "Desktop") are not available in side bar.

**Comment by phw** [comment]
You can give access to the ntfs partition just with the same `--filesystem` parameter, just pass the path to your mount point to it.

The bookmark thing is really only solvable with using GtkFileChooserNative (option 3 from above). That's actually implemented in Peek, but I build the Flatpak packages without it since it breaks the "open in file browser feature", which is rather essential to me.

**Comment by phw** [comment]
I have updated the Flatpak build files and future versions of Peek will come with full access to $HOME by default.

**Comment by glaubersm** [comment]
Thank you phw.
Have a nice day.
