### ISSUE TITLE
Add Keyboard Shortcuts

### ISSUE THREAD

**Issue by xd1936** [phw/peek#23]
This project is great! Keep up the good work.

Please add a keyboard shortcut for Peek, so that all of my GIFs don't end with my cursor moving to the top middle of the window I'm recording.

**Comment by phw** [comment]
One of the most important things on my todo list here and my top personal annoyance when recording :) I hope to have time to get this done soon.

**Comment by phw** [comment]
I have somewhat a solution for this. The current git master provides command line parameters to toggle the recording. So if Peek is already running you can run:

    peek --start

to start recording in the running instance. Likewise you can stop with `peek --stop`. Most useful is maybe `peek --toogle`, which will start or stop recording based on the current state.

The idea is that you can bind those commands to a global kyboard shortcut inside your desktop environment, e.g. in Gnome you can configure shortcuts in the preferences.

The problem with adding shortcuts directly to Peek is, that normal application shortcuts won't help, since you normally don't have Peek focused when recording. So you need global shortcuts. Global shortcuts however require integration in each desktop environment. Or you use X directly, but with things like Wayland and Mir knocking on the door this is not a very future proof implementation. So either way, this is quite some work to support it everywhere, so I am not sure I will do that. At least not soon.

**Comment by phw** [comment]
Started work on that. Keyboard shortcut is already working in latest master, it just needs a UI to configure it and maybe it needs to be disabled on Wayland because it should not work there anyway.

What do you think is a suitable default shortcut? For now it is `Ctrl+Alt+R`, does that make sense or does it clash with any important default?

**Comment by Deevad** [comment]
```Ctrl+Alt+R``` sounds good here. Thank you for the new feature!

**Comment by lode** [comment]
FYI, Gnome's screencast feature (https://help.gnome.org/users/gnome-help/stable/screen-shot-record.html.en) uses `Ctrl+Alt+Shift+R` by default.

**Comment by phw** [comment]
There is now a UI for changing the keyboard shortcut:

![bildschirmfoto vom 2017-02-28 14-37-56](https://cloud.githubusercontent.com/assets/29852/23410057/2a7d2cb8-fdce-11e6-83fe-6b32e40727a9.png)

**Comment by Bug-Reaper** [comment]
Yo shoutouts to @phw . I just mapped `peek --toggle` with a keybinding and it feels so good.
