### ISSUE TITLE
Freezes whole desktop on init

### ISSUE THREAD

**Issue by DylanC** [phw/peek#242]
The countdown goes 3, 2, 1 and then my PC is frozen completely. I have to hard press the power button to shutdown. Peek used to work on this machine but now it does not. 

Any ideas?

**Comment by phw** [comment]
Are you using Gnome (most likely even Gnome Wayland on Ubuntu 17.10)? If so, please see #202 and the Gnome Shell Bug at https://bugzilla.gnome.org/show_bug.cgi?id=790008

A quick workaround is to use X11 instead of Wayland, and if it still freezes use the ffmpeg backend instead of gnome-shell by starting Peek with `peek -b ffmpeg`. Note that this will only work on X11 anyway, so first try using X11.

**Comment by DylanC** [comment]
@phw - Apologies, I should have used the search first. Yes, I'm using 17.10 with Gnome. The strange thing is it worked for maybe 5 times and now stopped working entirely on Gnome.

I will try with X session and let you know how I get on.

**Comment by phw** [comment]
Closing as duplicate

**Comment by phw** [comment]
I opened a discussion at https://forum.snapcraft.io/t/screen-recording-on-wayland/3563
