### ISSUE TITLE
Request: setting the capture window size/position via text input

### ISSUE THREAD

**Issue by JobLeonard** [phw/peek#246]
Quite often when I capture part of the screen I want pixel precision: for example, an 800x600 gif, perfectly aligned to hide UI borders of an application. That can be really finicky to do with the mouse or touchpad. Being able to type in x, y, width and height somewhere would make things much easier.

I can of course also use [SimpleScreenRecorder](http://www.maartenbaert.be/simplescreenrecorder/) (which has such controls) to capture video first and then throw the captured video through gifsky, but you know... this would be more convenient :)

I don't know if this is something that window managers even let you do, so apologies if this is a very complicated request to implement, despite the apparent simplicity on the UX side!

**Comment by phw** [comment]
This also came up in #53. Not really high priority for me as I think if you want the ability to script this you are probably better off with using something like [ffcast](https://github.com/lolilolicon/FFcast) + ffmpeg directly. Also window positioning will work with XWayland, but won't work on native Wayland (but for now Peek requires XWayland anyway).

But I am open to accept pull requests. Peek already can save and restore the window size and position, that logic could be reused and be initialized with command line parameters. One thing that would need to be changed is having Peek restore the actual position and size of the recording area instead of the window position and size. I wanted to do this change anyway, as it would e.g. keep the recording area consistent between launches even if one changes the GTK theme.

**Comment by aoloe** [comment]
i would also wish, to to set a few "common" sizes (and eventually positions).
currently, iv'e solved it with a python script that allows me to set the size of any window.

```
+--------------+-+-+ +-----+
|1200 x 840    | v | | add |
+--------------+-+-+ +-----+
|800 x 1200        |
|1300 x 800        |
+------------------+
```

**Comment by Shrubhog** [comment]
If this was a menu option (hamburger menu button), where would it be positioned?

**Comment by aoloe** [comment]
i'm fine with having it in the preferences...

but it might also be right of the "record as" button in the top bar.

- the first value (the one showed) would be the current size of the window.
- it should be possible to type a value in this field.
- the other values would set the current size.
- the last entry would be "store as preset" (which would store the current size as preset).
- followed by "remove from preset" (to remove the current size from the presets... if any is matching; the alternative would be to put a minus or a trash bin right to each preset).

**Comment by aoloe** [comment]
this is still the important feature i'm missing in peek...
setting the size of the captured area is often painful...

**Comment by aoloe** [comment]
cool thanks!

i will test as soon i'll get a build
