### ISSUE TITLE
Video glitches when using Wayland with scaling

### ISSUE THREAD

**Issue by moqmar** [phw/peek#268]
I'm using Wayland with GNOME on Ubuntu 17.10 on a high dpi screen. If the screen scaling is set to 1 in the Gnome Settings, everything works as expected. Other values result in weird artifacts in the output video:

- Setting it to 200% results in a video containing skipped lines like this: https://vgy.me/QgMROh
- Using 150% results in skipped lines *and* columns, making the video completely unusable: https://vgy.me/cyFa2v

**Comment by phw** [comment]
For me this sounds like a video driver issue or something. What happens if you record you dektop using GNOMEs built-in screen recording (default `Shift + Ctrl + Alt + R`), does this have the same issues?

What if you start Peek with the ffmpeg backend:

    peek -b ffmpeg

**Comment by moqmar** [comment]
Well, `Shift + Ctrl + Alt + R` leads to a [complete system lockup](https://bugzilla.redhat.com/show_bug.cgi?id=1394755) under Wayland, no matter the scaling and/or computer. :D

`peek -b ffmpeg` results in just a black video, but with the correct resolution.

**Comment by phw** [comment]
The freezing is already reported at https://bugzilla.gnome.org/show_bug.cgi?id=790008 . Interesting that you are not affected by it when using Peek.

One last shot: Have you enabled gifski? The video issues visually remind me of a video issue gifski had in earlier releases. If so please try disabling gifski. Can you also try recording WebM to see if this issue is only limited to GIF?

If gifski is not involved and WebM also is broken this is definitely an upstream issue and should be reported in the GNOME bug tracker. Might be driver related, so make sure to also note which video card and driver you have.

> peek -b ffmpeg results in just a black video, but with the correct resolution.

If you are on Wayland this is to be expected ;) Sorry, I missed that information.

**Comment by moqmar** [comment]
WebM is broken too, gifski is not installed. So, I guess it is indeed a Gnome issue.
But thanks for the help. :)

**Comment by phw** [comment]
Closing this as an upstream issue. If screen recording is so seriously broken for you on Wayland I would suggest staying with X11 for the time being.

**Comment by moqmar** [comment]
Well, compared to Wayland X11 literally can't scale at all, so that would obviously solve that issue. :D
I still use X11 on my desktop computer where I don't need any scaling, and Peek works like a breeze there - together with the awesome UI it's a program I really like to use.

**Comment by moqmar** [comment]
Upstream issue on the GNOME bug tracker: https://bugzilla.gnome.org/show_bug.cgi?id=795189
