### ISSUE TITLE
gif size heavy size

### ISSUE THREAD

**Issue by devel0** [phw/peek#276]
**problem**: produced animated gifs are heavy in their size if compared to those produced by [record-screen](https://github.com/SearchAThing-forks/record-screen-gif)

**possible solution** : consider replacing the backend used for gif recording

**Comment by phw** [comment]
That's using gifsicle. I actually had not a good experience when I tried this, but I will have a look again.

Just to make sure: You are not using gifski, right? Because with gifski large sizes are to be expected.

**Comment by phw** [comment]
@devel0 Are you using gnome-shell? If so, #288 led to large files and this will be fixed in the next release.

Apart from that there is a feature request #291 to use giflossy (a forked gifsicle with lossy compression option), that's what's being used by record-screen. I have not yet done testing and can't say for now whether it will bring any advantage.

Using the plain gifsicle has no advantage. Compared to the default ffmpeg encoder used by Peek I got files nearly 30% larger with dithered colors.

I will close this issue, since both #288 and #291 cover this already.

**Comment by devel0** [comment]
Thank you for the update, I will try development version too.
To now I attached a test with my current Ubuntu peek version at [this link](https://1drv.ms/f/s!Ai8dQ5VqOIUihq5R8zc3uBLA96renA) that shows a 600k vs 173k file size of the same record ( note mismatch colors on avatar due to overlap of reocordings preview 3,2,1 timer ).

My current config follows:
- peek 1.2.2
- screen_record ( [version](https://github.com/SearchAThing-forks/record-screen-gif/commit/8608742177a424a9b8c6f5dfcc53e07ba489ec23) )
- os
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```
- gnome
```
# gnome-shell --version
GNOME Shell 3.26.2
```

**Comment by phw** [comment]
Thanks. Would also be great if you could see if there are differences for you when using `peek -b gnome-shell` vs. `peek -b ffmpeg`. In the current development version this should be pretty much the same.

**Comment by devel0** [comment]
I confirm that latest peek version ( 1.2.2 ) works generating gif with size almost equal to those generated with screen recorder. [Example](https://1drv.ms/f/s!Ai8dQ5VqOIUihq5V18vzhBnVJ_NRCA).

thank you

**Comment by phw** [comment]
Great, good to hear. I have actually some issues here with the new setup, conversion to GIF sometimes fails now. But I am on it and will figure out how to fix this.
