### ISSUE TITLE
Very noisy terminal recordings

### ISSUE THREAD

**Issue by skerit** [phw/peek#288]
The resulting gif of a terminal recording is very noisy.

Here's a frame where I moved the cursor, but all the text in the terminal has some noise surrounding it.

![afbeelding](https://user-images.githubusercontent.com/755212/37048614-ab7a1f28-216e-11e8-90ae-cd61fb09cdf9.png)

I've been able to create gifs of about 500 KiB using byzantine & gifsicle, but with peek I can barely get under 10 MiB. Any idea how to solve this?

**Comment by phw** [comment]
Are you recording on Gnome? If so, could you try and see whether recording with the ffmpeg backend (start Peek with `peek -b ffmpeg`) does make any difference?

**Comment by phw** [comment]
I can reproduce this by comparing results from the gnome-shell and ffmpeg backend. I am actually not surprised, the ffmpeg uses a lossless video as source for GIF generation, while gnome-shell backend uses a high quality but lossy video.

I have to figure out what option gstreamer offers for lossless video by default.

**Comment by skerit** [comment]
Just to confirm: I was indeed using gnome-shell.

**Comment by phw** [comment]
I did some testing and I will go with VP9 encoder here. With highest quality settings I got perfectly clean frames when no changes happened, even though gstreamer does not seem to support the explicit "lossless" option that the reference encoder offers.

Just to sumarize and clarify the problem here for later reference:

Peek on Gnome by default uses Gnome Shell's built-in screen recorder, because that's also working on Wayland. That screen recorder uses gstreamer, and when invoking the Gnome Shell recorder Peek passes a [custom gstreamer pipeline](https://github.com/phw/peek/blob/master/src/recording/gnome-shell-dbus-recorder.vala#L115).

For GIF generation you want lossless video, since you want to avoid any artifacts that would increase the colors or lead to dirty frames as shown above. My requirements are:

- The resulting video file should be small, as it will be stored as a temporary file and space there might be limited
- The video must be lossless
- Saving as individual frames, e.g. as PNG, does not work, as the gnome-shell recorder expects a single output in the pipeline

The use of VP9 seems to satisfy these conditions.
