### ISSUE TITLE
create vp9 webm files

### ISSUE THREAD

**Issue by aoloe** [phw/peek#293]
currently, peek is creating webm with the vp8 video codec.

it would be nice to (optionally?) create them with the vp9 codec.

i've searched through the source code and i've seen that there are already some preparation that has been done...

**Comment by phw** [comment]
Yes, as you've seen I already made some changes and even considered it. As my aim was to make everything as compatible as possible by default, and also because I was not sure which versions of ffmpeg and gstreamer would be needed, I had left the VP8 as default.

But I am happy to add VP9. Maybe I'll just add two entries for webm: WebM (VP8), WebM (VP9). Or some advanced tab with per format options.

**Comment by phw** [comment]
I wonder if there is any good reason to use VP8. I tried to find something about compatibility, but VP8 / VP9 supports seems to go hand-in-hand wherever I looked. @aoloe Any opinion on this? I tend to just change this over to VP9 and ignore VP8, as it offers no advantages.

**Comment by aoloe** [comment]
the less options, the better : - )

i have not much experience with video and codecs, so my opinion is not really relevant...
but i'm creating a workflow around webm with VP9 and -- for what i'm doing -- it's much faster and produces smaller files.

if nobody has a technical objection, i'm for VP9 only...

**Comment by phw** [comment]
I changed it to VP9. Let's see, I personally have no issue with this. If somebody comes up and as good reasons to use VP8 instead I will add an option to configure it.

**Comment by hockeymikey** [comment]
> I changed it to VP9. Let's see, I personally have no issue with this. If somebody comes up and as good reasons to use VP8 instead I will add an option to configure it.

I need this option. Tried posting in places that only allowed VP8 so a setting would be amazing.
