### ISSUE TITLE
why are files so big?

### ISSUE THREAD

**Issue by nunodonato** [phw/peek#3]
So I'm recording some tiny GIFs (around 400px wide) at 15fps, and still get big file sizes.
Twitter sets a limit at 5mb per gif, so I can _never_ use a gif captured with Peek. Yet, I see constantly long gifs with good quality... whats the catch?

thanks for the awesome tool :)

**Comment by phw** [comment]
Sorry for the way too late reply :(

I can't really tell you why your file is so big without more information. What exactly is "big" and "long"?

In general ImageMagick is used to convert the animation to GIF and it does a very decent job in minifying the frames: Each frame will only contain the data that differs from the one before.

In general for animated GIFs there are a few rules to follow for good results:

* Use a low framerate. 15fps seems to work quite well for me
* Avoid too much change. If there is heavy animation the frames will differ a lot
* Avoid too many colors, since GIF is limited to a 256 color pallette. This one is not so much about file size but more about visual quality.

Otherwise I'd need some real world comparison to tell you more, e.g. an animation you think is large and not so big and a comparable animation you recorded with peek which you consider too big.

**Comment by chteuchteu** [comment]
I used to use ScreenToGif on Windows to record gifs: please know that I'm delighted there's a Linux alternative!

I used ScreenToGif to record the following gif ([used in one of my projects' README](https://github.com/chteuchteu/MaterialDesignIcons-SCSS-Variables)):
![screenshot](https://cloud.githubusercontent.com/assets/1551971/18143062/c366d57e-6fc0-11e6-8e84-e78014ce6a42.gif)

In order to compare file sizes, I recorded quite the same animation with Peek:
![peek 2016-08-31 21-19](https://cloud.githubusercontent.com/assets/1551971/18143082/d75dd406-6fc0-11e6-83f4-b32410563c41.gif)

Even if these are not quite comparable, they are still based on the same filesize scale (framerate, colors amount, duration, "change rate"/animation speed).

**Here's the conclusion: ScreenToGif produced a 58,2 kB file while Peek saved a 16,6 kB file.** Peek wins!
Should this issue be closed? We could mention it somewhere in the documentation though, or lead some more tests

**Comment by phw** [comment]
Thanks @chteuchteu for doing this investigation. It is also my suspicion that Peek is already doing a nice job (thanks to imagemagick in this case) of reducing the file size. In the end Gif is just not well suited for doing large animations with a lot of changes, as the optimization completely depends on just having the differences in each frame. I lean toward closing this, but maybe we should have some kind of FAQ first :)

**Comment by chteuchteu** [comment]
+1 for the FAQ!

**Comment by phw** [comment]
I have added a FAQ to the README

**Comment by davidricardo1026** [comment]
ScreenToGif now is really small and peek is really large.
maybe There is a new optimization in ScreenToGif
