### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Hedgehogues** [phw/peek#304]
Peek: 1.3.1
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 1533x833 -i :0+66,66 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/urvanov/.cache/peek/peekONV9GZ.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 7.2.0 (crosstool-NG 8a21ab48)  configuration: --prefix=/home/urvanov/anaconda3 --disable-doc --enable-shared --extra-cflags='-fPIC -I/home/urvanov/anaconda3/include' --extra-cxxflags='=-fPIC' --extra-libs='-L/home/urvanov/anaconda3/lib -lz' --enable-pic --disable-static --disable-gpl --disable-nonfree --disable-openssl --enable-libvpx --cc=/home/urvanov/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc --cxx=/home/urvanov/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ --enable-libopus  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100Unrecognized option 'show_region'.Error splitting the argument list: Option not found
```

**Comment by phw** [comment]
This seems to be some issue that the ffmpeg from /home/urvanov/anaconda3/bin/ is used. This is not the first time and project I see anaconda messing up things, since it tends to install tons of binaries and libraries and hides the system provided ones.

Please start Peek with a $PATH variable that does not contain /home/urvanov/anaconda3/bin/, or at least has the system ones at the front.

**Comment by phw** [comment]
I added a bug report for Anaconda: https://github.com/ContinuumIO/anaconda-issues/issues/9138

Maybe they will fix their behavior, which is pre-programmed to cause issues like this. In any way, you as a user should fix your $PATH.

**Comment by mingwandroid** [comment]
We do not recommend people modify their PATH permanently or globally. When they want to use Anaconda they should activate it as that sets PATH for that session only.

**Comment by phw** [comment]
@mingwandroid Ok, thanks for the heads up. So the PATH modification is a separate step done by the user, but is neither recommended nor documented that way? That makes sense.

That probably means I can close https://github.com/ContinuumIO/anaconda-issues/issues/9138 again :) I just felt like bringing this up since I got a similar issue reported twice already, and it looked to me like a general issue Anaconda handled this.

**Comment by mingwandroid** [comment]
We are reforming our ways around this I would say!

We still offer an option to modify PATH on Unix but now warn against it on Windows at least. I'll try to make sure that for the next release we push the activate way on all OSes since it's far better for everyone.
