### ISSUE TITLE
help me I am on endlessos

### ISSUE THREAD

**Issue by DevSaurabhcb** [phw/peek#309]
Peek: 1.3.1
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment]
The error often indicates missing gstreamer plugins. You need at least the gstreamer "good" plugins installed. If you want to record MP4 you also need the "ugly" plugins.

If this is not the issue a look at `journalctl -f` while triggering this error in Peek should show more details on the reason.

If the above doesn't help there is always the possibility to use the ffmpeg backend instead of the gnome-shell one by running Peek with `peek -b ffmpeg`

**Comment by phw** [comment]
I am considering this answered. Please let me know and provide more details if this is not the case.
