### ISSUE TITLE
Random build failure with parallel build

### ISSUE THREAD

**Issue by hosiet** [phw/peek#312]
From https://bugs.debian.org/895580#17 : 

> I've been having a few problems when building the package locally.  It's
> a build failure due to a missing header, and the strange thing is that
> it happens intermitently (i.e., sometimes I can build everything just
> fine, sometimes the build fails).  Here's the error:
> 
>   /build/peek-debian/peek-tmp/obj-x86_64-linux-gnu/src/utils.c:16:10: fatal error: application.h: No such file or directory
>    #include "application.h"
>             ^~~~~~~~~~~~~~~
>   compilation terminated.
>   make[4]: *** [tests/CMakeFiles/peek-test-utils.dir/build.make:126: tests/CMakeFiles/peek-test-utils.dir/__/src/utils.c.o] Error 1
>   make[4]: *** Waiting for unfinished jobs....
> 
> After spending some time tracking down the issue, what I found is that
> "application.h" is generated automatically by Vala (see the
> "vala_precompile" rule on CMakeLists.txt).  I've compared the build logs
> generated by a successful build against those generated by an
> unsuccessful one, and there's nothing really wrong that I see.  Plus, if
> I rerun the "make" command after the failure the build succeeds.  So
> far, this is telling me that the problem seems to be a race condition
> (due to the way cmake parallelizes the jobs, maybe).

**Comment by phw** [comment]
Thanks for this analysis. I already observed this random build errors when building the Arch package, but could not find the cause. But this is a likely explanation, as doing parallel build is the difference of my Arch package builds and doing local builds during development (where I never observed this issue).

I will try looking into this, but I don't have much experience with cmake, so any hint in debugging this is welcome.

**Comment by phw** [comment]
So I played with this, but currently was not able to reproduce the build failure. Tried with `make` and various `make -jn` variations.

One possible workaround could be to use ninja instead of make (by using `cmake -Gninja`), but of course this introduces yet another build time dependency. Also not sure if this really fixes the issue, but at least I have never seen it happen when using ninja.

Some similar issue is at https://www.bountysource.com/issues/47981582-parallel-builds-fail-due-to-race-condition , but no fix. They just moved to meson, which made the issue obsolete.

**Comment by phw** [comment]
Ok, I found something, and that is likely an error in Peek's build files: The issue is easily reproducible if building the tests is enabled with `cmake -DBUILD_TESTS=ON`. In this case `make -j8` is very likely to cause the issue for me, lower numbers not so much (makes sense, less race competitors).

When building with tests some build targets are duplicates, there are warnings such as:

```
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:126: warning: overriding recipe for target 'src/recording/recording-area.c'
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:97: warning: ignoring old recipe for target 'src/recording/recording-area.c'
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:135: warning: overriding recipe for target 'src/defaults.c'
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:112: warning: ignoring old recipe for target 'src/defaults.c'
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:138: warning: overriding recipe for target 'src/utils.c'
tests/CMakeFiles/peek-test-screen-recorder-cli-screen-recorder.dir/build.make:118: warning: ignoring old recipe for target 'src/utils.c'
```

This seams to be the source of all the race conditions. I am pretty sure I am doing something bad in https://github.com/phw/peek/blob/master/tests/CMakeLists.txt, but I don't know exactly how I should fix this. Will do some research, but any help appreciated.

**Comment by gort818** [comment]
Maybe we should move to meson? Obliviously it is like putting a band-aid on the issue but it seems meson is the future.

**Comment by phw** [comment]
So I started adding Meson build files in #321. I cannot say yet if it solves the issue here, since I haven't added building the tests yet, but I am optimistic.

In any way, this is the very first time I use Meson, so I would appreciate some feedback if someone has some more experience in this. So far I already like it, the entire syntax and structure is much more sane than CMake :)

**Comment by phw** [comment]
@hosiet You have several options right now. For the current release I recommend building with CMake, but without the tests:

    cmake -DBUILD_TESTS=OFF

This should successfully allow parallel builds. Alternatively build using CMake + Ninja

    cmake -GNinja

Going forward I would recommend to use Meson, I will do a new release soon. The next release will allow both CMake and Meson, but I will drop CMake support at some point (rather sooner than later).

**Comment by hosiet** [comment]
@phw I finally have some time to dig into it and here's my analysis:

It is clear that the problem is caused by the uncertain build order when doing multi-threaded build. We know that tests need `application.h`, which is generated by valac during the build of main `peek` executable. As a result, we can force all tests target to depend on the main peek executable target.

Patch attached here:

```diff
rom: Boyuan Yang <073plan@gmail.com>
Date: Wed, 13 Jun 2018 18:07:42 +0800
Subject: tests: Force build tests after main executable target

---
 tests/CMakeLists.txt | 16 ++++++++++++++++
 1 file changed, 16 insertions(+)

diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 23a4db3..087d0ca 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -17,6 +17,10 @@ add_test(
   test-desktop-integration
   ${PROJECT_NAME}-test-desktop-integration)
 
+add_dependencies(
+  ${PROJECT_NAME}-test-desktop-integration
+  ${PROJECT_NAME})
+
 # /utils/
 vala_precompile(VALA_TEST_UTILS_C
     test-utils.vala
@@ -34,6 +38,10 @@ add_test(
   test-utils
   ${PROJECT_NAME}-test-utils)
 
+add_dependencies(
+  ${PROJECT_NAME}-test-utils
+  ${PROJECT_NAME})
+
 # /screen-recorder/recording-area/
 vala_precompile(VALA_TEST_RECORDING_AREA_C
     screen-recorder/test-recording-area.vala
@@ -50,6 +58,10 @@ add_test(
   screen-recorder-test-recording-area
   ${PROJECT_NAME}-screen-recorder-test-recording-area)
 
+add_dependencies(
+  ${PROJECT_NAME}-screen-recorder-test-recording-area
+  ${PROJECT_NAME})
+
 # /screen-recorder/cli-screen-recorder/
 vala_precompile(VALA_TEST_COMMAND_LINE_SCREEN_RECORDER_C
     screen-recorder/test-cli-screen-recorder.vala
@@ -79,3 +91,7 @@ add_executable(
 add_test(
   test-screen-recorder-cli-screen-recorder
   ${PROJECT_NAME}-test-screen-recorder-cli-screen-recorder)
+
+add_dependencies(
+  ${PROJECT_NAME}-test-screen-recorder-cli-screen-recorder
+  ${PROJECT_NAME})
```

It is tested that peek won't fail to build after applying this patch.

**NOTE** This patch is based on 1.3.1 release. You may need to rebase it against latest git HEAD.

@phw Do you think it is an acceptable approach?

**Comment by phw** [comment]
@hosiet Thanks a lot for the analysis and the patch. Yes, that patch makes sense for this case, I have applied your commit to master.

Having said this I will go forward with Meson and will make it the default build system for Peek. Using Meson has been a very smooth and pleasant experience. Compared to CMake setting everything up took far less time with Meson.

However, since Peek currently needs a rather new version of Meson which is not easily available on older distributions I will keep the CMake build around for a while. Just consider CMake officially deprecated, it will only get the necessary updates going forward.
