### ISSUE TITLE
Foreground window is flashing in generated gif

### ISSUE THREAD

**Issue by bbbenji** [phw/peek#395]
When reviewing the created recording, the top window in view disappears several times showing whatever is below it. This does not occur during the actual recording. The flashing only appears on the actual recording.

Attached is an example: https://gfycat.com/TenseImpoliteCoqui

This seems to happen every time.

benji@think ~/t/www> uname -a
```
Linux think 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux
```

benji@think ~/t/www> hwinfo --short
https://hastebin.com/rovobusunu.makefile

**Comment by derekhawker** [comment]
I had this issue but it was independent of Peek (also happened when I use other screen recorders). There could be several issues, but for me it was fixed by changing my "AccelMethod" from "**sna**" to "**uxa**"  in my x11 xorg conf

https://wiki.archlinux.org/index.php/Intel_graphics#SNA_issues

/etc/X11/xorg.conf.d/
```
Section "Device"
    Identifier  "Device0"
    Driver      "intel"
    BusID       "PCI:0:2:0"
##    Option      "AccelMethod" "sna"
    Option      "AccelMethod" "uxa"
	Option      "DRI"    "true"
EndSection
 ```

**Comment by phw** [comment]
What @derekhawker wrote, this usually indicates issues with the video driver. See also https://github.com/phw/peek#my-recorded-gifs-flicker-what-is-wrong
