### ISSUE TITLE
Ability to record the top of the screen.

### ISSUE THREAD

**Issue by ripefig** [phw/peek#520]
Most other screenshot and screen recorder utils just allow you to draw a square anywhere, but peek has a fixed titlebar. This makes the top of the screen difficult-to-impossible to record. So you can no longer file a bug report about a panel, for example.

I'd propose separating the recording area from the interface, like all other utilities of this kind. 

I.e. the controls and the recording rectangle float independently. This would make the app much more flexible. Another (worse) idea would be to have a header bar hiding shortcut that would turn the window into just a plain rectangle.

**Comment by phw** [comment]
> I'd propose separating the recording area from the interface, like all other utilities of this kind.

I'm sorry, but I will close this a wontfix. Peek basically only exists because I wanted exactly this interface and not like other screenshot utilities a separate action to draw a rectangle. I can't change this without loosing myself as a user.

Given that Peeks use case is to record only a small part of the complete screen it usually is possible to move the things to record a bit down.

**Comment by ripefig** [comment]
It could be an option @phw. Hiding the headerbar on demand might be simplest solution. 

I know GTK software and features don't typically mix but it would solve a few important corner cases. The other utilities don't export to gif, don't support wayland and have really clunky interfaces.
