### ISSUE TITLE
Video starts to lag after 1 second of recording

### ISSUE THREAD

**Issue by younyokel** [phw/peek#545]
Hey, it's a great application. You can see I have this problem on my Elementary OS system:
[![Peek-2020-01-30-20-00.gif](https://i.postimg.cc/3R199pBS/Peek-2020-01-30-20-00.gif)](https://postimg.cc/JDybzsSZ)
I set my FPS to 30 and the computer doesn't lag itself while recording.

That's actually everything I can say to you. Sorry.

**Comment by younyokel** [comment]
You can see that it doesn't lag in first 1 seconds of the video, also this happens not only with gif recordings. I tried WebM and it was the same.

**Comment by CurunirCingar** [comment]
Same. I can't use your app because of it :disappointed:

**Comment by CurunirCingar** [comment]
I really want to make it work so I ran app from source with extra logs and made several tests.
for now I understood that it's not Peek's issue but ffmpeg's one. If I run same command as Peek does:
`ffmpeg -loglevel debug -f x11grab -show_region 0 -framerate 25 -video_size 1550x506 -i :0+369,452 -filter:v scale=iw/2:-1 -codec:v libvpx-vp9 -r 25 -y /home/curunir/.cache/peek/peekT13SF0.webm`
I clearly can see lagging in result of ffmpeg .webm file.
Can someone try it on your computer?
For now I suggest that it ffmpeg lags when it writes screencast into a file.

**Comment by phw** [comment]
@CurunirCingar Thanks a lot for this investigation. I can unfortunately not reproduce this myself, but of course this does dependent on the system and depending on where the actual bottleneck is CPU or disk IO.

What could make a difference is using VP8 instead of VP9 as VP9 encoding can be more resource intensive. Could you test whether replaced the codec from `libvpx-vp9` to just `libvpx` improves the result?

**Comment by CurunirCingar** [comment]
@phw yes It helped. With `libvpx` codec no lagging occurred.
I have logs for runs with both codecs:
[libvpx.log](https://github.com/phw/peek/files/4191740/libvpx.log)
[libvpx-vp9.log](https://github.com/phw/peek/files/4191741/libvpx-vp9.log)
And recorded screencasts: [videos.zip](https://github.com/phw/peek/files/4191784/videos.zip)

I have HDD and SSD on my machine:
```
/dev/sda:
 Timing cached reads:   29062 MB in  1.99 seconds = 14632.51 MB/sec
 Timing buffered disk reads: 404 MB in  3.00 seconds = 134.46 MB/sec
```
 ```
/dev/nvme0n1:
 Timing cached reads:   27580 MB in  1.99 seconds = 13869.76 MB/sec
 Timing buffered disk reads: 5400 MB in  3.00 seconds = 1799.70 MB/sec
```
So I thought that it could be because of slow HDD, but I got same laggy result when saving file on SSD.
[libvpx-vp9-ssd.log](https://github.com/phw/peek/files/4191850/libvpx-vp9-ssd.log)
Also I have `Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz` and 16 Gb of RAM, so I don't think that it's because of specs.
