### ISSUE TITLE
Save dialogue confusing

### ISSUE THREAD

**Issue by hellocatfood** [phw/peek#55]
When saving a gif the dialogue box is confusion and the function of the buttons is a bit ambiguous

![screenshot from 2016-12-27 15-54-31](https://cloud.githubusercontent.com/assets/151947/21504236/f984a28a-cc54-11e6-80dc-d2669a2ee4d5.png)

Should the icon be an alert icon? As it's information can the blue "i" icon be used? Also, is there a difference between what pressing Cancel and OK do?

**Comment by hellocatfood** [comment]
Thanks for the clarification. What should the dialogue look like? I'm using Unity on Ubuntu 16.04.

**Comment by phw** [comment]
There should be no dialog at all, just a desktop notification. Haven't used Unity for a long time, but I think it notifications show up in the upper right.

The fix should be rather easy by just removing the extra button I add to the notification. I think that's what's triggering the dialog to show.

**Comment by phw** [comment]
Issue indeed was that Unity does not allow actions in desktop notifications, because the notifications are not clickable. As soon as there is any action it will show a dialog instead.

Fixed this by removing the action. A workaround is to enable "Open in file manager" in the options, this will open the file manager directly and will not show the notification at all.
