### ISSUE TITLE
gifski not automatically from ppa but Flatpak.

### ISSUE THREAD

**Issue by D4N13L1980** [phw/peek#571]
Peek 1.5.1 

The ubuntu ppa version does not automatically use gifski.
The Flatpak version automatically use gifski.

Ubuntu 18.04.04

**Comment by phw** [comment]
Have you installed gifski?

As the flatpak version bundles everything it also includes gifski. But if you use distribution packages gifski needs to be installed separately (by package or manually).

**Comment by D4N13L1980** [comment]
Yes, I installed gifski with brew but the gifski options are only available in the Flatpak version.

**Comment by D4N13L1980** [comment]
Okay, if I run gifski from terminal:

```
Command 'gifski' not found, but can be installed with:

sudo snap install gifski
```

Flatpak seams to find the brew installation of gifski but ppa not.
After installing the snap gifski the ppa Peek is happy.

**Comment by phw** [comment]
You must make sure that bthe gifski is available in your path so Peek can find it. I don't know where brew places the executable, but you probably need to adjust your `PATH` variable for this to work. But happy to see the snap solution worked for you.

Flatpak version is different because it has its own gifski bundled (and cannot access the other one anyway due to sandboxing)

**Comment by D4N13L1980** [comment]
I didn't know that the Flatpak version has its own gifski ^^
Thanks!
