### ISSUE TITLE
Peek won't recognize available recording backend on Arch Linux (ffmpeg)

### ISSUE THREAD

**Issue by o-alquimista** [phw/peek#614]
> OS: Arch Linux (x86_64)
> Peek version 1.5.1 (from the [community](https://www.archlinux.org/packages/community/x86_64/peek/) repository)
> Desktop Environment: Xfce 4.14

Peek won't start. All I get is a dialog saying:
```
Unable to initialize default recording backend: Peek requires FFmpeg or running GNOME Shell session.
```
[ffmpeg](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/) is installed, and is available on the PATH.

Here's the output of `G_MESSAGES_DEBUG=all peek`:
```
(peek:2341): GLib-GIO-DEBUG: 20:01:34.406: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(peek:2341): GLib-DEBUG: 20:01:34.426: unsetenv() is not thread-safe and should not be used after threads are created
(peek:2341): Gtk-DEBUG: 20:01:34.426: Connecting to session manager
(peek:2341): Gtk-DEBUG: 20:01:34.426: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
** (peek:2341): DEBUG: 20:01:34.427: desktop-integration.vala:168: Desktop: XFCE
(peek:2341): GLib-GIO-DEBUG: 20:01:34.427: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(peek:2341): dconf-DEBUG: 20:01:34.427: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(peek:2341): dconf-DEBUG: 20:01:34.427: unwatch_fast: "/org/gnome/desktop/interface/" (active: 0, establishing: 1)
** (peek:2341): DEBUG: 20:01:34.427: application.vala:296: GTK theme: Adwaita
** (peek:2341): DEBUG: 20:01:34.427: desktop-integration.vala:168: Desktop: XFCE
(peek:2341): dconf-DEBUG: 20:01:34.427: watch_fast: "/com/uploadedlobster/peek/" (establishing: 0, active: 0)
(peek:2341): dconf-DEBUG: 20:01:34.427: watch_established: "/org/gnome/desktop/interface/" (establishing: 0)
(peek:2341): dconf-DEBUG: 20:01:34.427: watch_established: "/com/uploadedlobster/peek/" (establishing: 1)
** (peek:2341): DEBUG: 20:01:34.428: application.vala:221: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

** (peek:2341): DEBUG: 20:01:34.428: desktop-integration.vala:168: Desktop: XFCE
(peek:2341): GLib-DEBUG: 20:01:34.428: posix_spawn avoided (fd close requested) 
** (peek:2341): DEBUG: 20:01:34.429: utils.vala:72: Error: Falha ao executar processo filho “which” (Arquivo ou diretório inexistente)
Unable to initialize default recording backend: Peek requires FFmpeg or running GNOME Shell session.
** (peek:2341): DEBUG: 20:01:36.340: application.vala:112: Application got shutdown signal
(peek:2341): dconf-DEBUG: 20:01:36.342: sync
```

**Comment by o-alquimista** [comment]
As I was installing Catfish (the file search tool for Xfce), I noticed that one of its dependencies was a package named `which`, which is mentioned in the debug logs above:
```
Error: Falha ao executar processo filho “which” (Arquivo ou diretório inexistente)
```

After installing this [package](https://www.archlinux.org/packages/core/x86_64/which/), Peek works. Yay! :sweat_smile:  I hope this helps Arch users with the same problem in the future.

So, what should I do? Should I ask the package maintainer to add `which` as a dependency of Peek?

**Comment by eli-schwartz** [comment]
I would just like to point out that this is actually terrible and you should not be forking off subprocesses in order to run external programs that aren't portable and may not exist, just to find out whether another program exists.
https://github.com/phw/peek/blob/83fb30b30e5d833662c760a75e1b500d6d7ad1cc/src/utils.vala#L55-L76


Instead, you should use the programming language specific bindings that do the same thing as `which`, but are guaranteed to exist.

e.g. https://valadoc.org/glib-2.0/GLib.Environment.find_program_in_path.html

And, to finish off with a general note about why not to use `which` even if you know it exists... https://unix.stackexchange.com/a/85250/264819

**Comment by phw** [comment]
Yep, that must be changed. No need to change anything on the Arch side actually, this needs to be fixed in peek.

@eli-schwartz You should seriously think about your attitude and the way you communicate with people. There is a reason you frequently run into arguments with people. Just saying.

**Comment by eli-schwartz** [comment]
That wasn't a moral judgment... The world is full of people top to bottom misusing `which` (in large part because the Debian policy manual chose it instead of `command -v` for *.deb maintenance scripts in a pre-POSIX 2008 world and took until extremely recently, that is, mid-2018, to bump the policy and until barely last month to add the functionality to Debian's official policy shell implementation; bureaucracy is real). There are also programming languages where the **official stdlib implementation** of "find the executable in path" is to shell out to `which`, and the xdg-utils programs are full of bugs due to this and similar shell scripting failures. I'm hardly attempting to call you a bad person for doing it though...

Doesn't make it any less dangerous to rely on. It's incorrect to do it, I've gone out of my way to document why, and researched a robust, cost-free alternative for you to use instead.

If you find my absolutism (regarding whether or not `which` is appropriate technology for use in software development) offensive, then oh well. I do absolutely believe it, it has bad results, and nothing will ever change that or my opinions on the topic. I will continue to educate people when I see it used, about its deceptive, unexpected dangers that most people are not aware of, but which are worse than merely "it is slow because it requires a fork+exec".

At any rate, I don't believe we are in an argument about whether to switch to GLib functions?

**Comment by Relect** [comment]
the same problem
`it is not possible to initialize the server side of the record by default: peek requires FFmpeg or a running GNOME shell session`
fedora 34, gnome 40
