### ISSUE TITLE
Doesn't record apps not on current desktop

### ISSUE THREAD

**Issue by stuaxo** [phw/peek#674]
To reproduce:

Start recording an app.

In your desktop environment change to another desktop.

When you return and play the video generated you will see it recorded the desktop that was changed to.

Tested in GNOME.

**Comment by phw** [comment]
Yes, it's recording what is visible on your screen. I don't think it is possible to do this otherwise. This is definitely a won't fix, sorry

**Comment by stuaxo** [comment]
Ah, this is unfortunate.   Is this a limitation of GNOME shell ?

If it's not possible, then I'd really like to open know where the limitation is so I can open a feature request upstream.

**Comment by phw** [comment]
Peek uses either ffmpeg (X11 only) or the GNOME shell screen recorder (same interface for X11 and Wayland) for the actual recording. I can't tell you if it is technically feasible to record things that are not rendered. The answer likely differ depending on the backend being used and whether this is on X11 or Wayland. I can imagine that this is not feasible for ffmpeg, because it just grabs the pixels from X and your desktop's virtual desktops is at a higher level. No idea about gnome shell's screen recording, maybe this is something doable there.

But I don't know any screen recorder which you can instruct to record a specific virtual desktop instead of the, well, screen.
