### ISSUE TITLE
What is `libcrystalhd.so.3` and why is it needed?

### ISSUE THREAD

**Issue by CRISPYricePC** [phw/peek#675]
I can't find a reference to this library anywhere. I've tried completely uninstalling ffmpeg and it's still saying the library is missing. I've even checked with a friend and they said that they don't have that library on their system.

Why does ffmpeg want to use this library?

Peek: 1.5.1
GTK: 3.24.21
GLib: 2.64.4
Desktop: i3
Display server: X
FFmpeg version:
```

```

Output format: gif
gifski enabled: false

Error details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 613x496 -i :0+1248,930 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/benjo/.cache/peek/peek9E9DU0.webm" failed with status 32512 (received signal 0).

Output:
ffmpeg: error while loading shared libraries: libcrystalhd.so.3: cannot open shared object file: No such file or directory
```

**Comment by phw** [comment]
Looks like libcrystalhd is the user space part for  Broadcom Crystal HD video decoder devices.

In your case the ffmpeg was compiled against this. What distro are you using and how have you installed ffmpeg? If ffmpeg is provided by your distro they should also have libcrystalhd (actually the ffmpeg package shod have set it as a dependency).

If you have installed ffmpeg from elsewhere you either need to either install libcrystalhd or use a ffmpeg not compiled against libcrystalhd.

**Comment by CRISPYricePC** [comment]
I've installed it via Pacman on ArchLinux. What's odd is I have a friend on arch who doesn't have libcrystalhd and their system works fine. I think there's a broken config involved since building ffmpeg also gives the error. Either that or I have broken dependencies

**Comment by phw** [comment]
I don't have an Arch install currently to test this, but the official build of ffmpeg in the arch repos does not depend on libcrystalhd. Actually libcrystalhd  is not even part of the repos (but is available in AUR).

I really don't know if and how ffmpeg can make use of libcrystalhd. It's also possible it is not ffmpeg itself but a dependency of ffmpeg which then depens on libcrystalhd.

I would suggest you check which packages you have installed from AUR or elsewhere (`pacman -Qm`) and see if some of those packages are direct or indirect dependencies of ffmpeg.

Otherwise please bring this issue to the Arch forums, they can help you better on this.
